version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
      BUILD_CONFIG: Release
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Debug
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: deploy when exists tag
          command: |
            if [ "${CIRCLE_TAG-undefined}" != "undefined" ]; then
              dotnet build -c Release -p:Version=${CIRCLE_TAG}
              dotnet pack ./src/SkiaSharp.QrCode/SkiaSharp.QrCode.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
              dotnet nuget push ./src/SkiaSharp.QrCode/bin/Release/SkiaSharp.QrCode.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
            else
              echo tag not exists
            fi
      - store_artifacts:
          path: ./src/SkiaSharp.QrCode/bin/Release
          destination: ./SkiaSharp.QrCode/
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^[0-9](\.[0-9]){2}$/
            branches:
              only: master
